### => GET TEST
GET http://localhost:3000/post/teste

### => GET ALL
GET http://localhost:3000/post

### => GET BY ID
GET http://localhost:3000/post/60ce88c9d92bce34d8c64cea

### => CREATE
POST http://localhost:3000/post/create
Content-Type: application/json

{
  "titulo" : "Olo",
  "descricao" : "Vovo"
}

### => UPDATE
PUT http://localhost:3000/post/update/60ce88c9d92bce34d8c64cea
Content-Type: application/json

{
  "titulo" : "Eae",
  "descricao" : "Galeraaa"
}

### => DELETE ALL
DELETE http://localhost:3000/post/delete